version: '2'
services:
  web:
    image: icalialabs/alpha:dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: yarn start
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment: &app_environment
      PATH: /usr/src/app/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      NODE_ENV: development
